---

- name: Install ansible-pull wrapper script
  copy:
    src: files/ansible_pull_wrapper.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: Install systemd files
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: '0644'
  with_items:
    - ansible_pull.service
    - ansible_pull.timer
  notify:
    - Reload systemd files
    - Enable ansible_pull service
