---

- name: Install ansible-pull wrapper script
  ansible.builtin.copy:
    src: files/ansible_pull_wrapper.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- name: Create ansible-pull service override directory
  ansible.builtin.file:
    path: /etc/systemd/system/ansible_pull.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install systemd files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - ansible_pull.service
    - ansible_pull.timer
    - ansible_pull.service.d/90ansible-pull-defaults.conf
  notify:
    - Reload systemd files
    - Enable ansible_pull service
