---

- name: Install ansible-pull wrapper script
  copy:
    src: files/ansible_pull_wrapper.sh
    dest: /usr/local/bin

- name: Install systemd files
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
  with_items:
    - ansible_pull.service
    - ansible_pull.timer
  notify:
    - Reload systemd files
    - Restart ansible_pull service
