---
- name: Reload systemd files
  ansible.builtin.systemd:
    daemon_reload: yes

# TODO use service module when fixed
# https://github.com/ansible/ansible/issues/48786
- name: Enable ansible_pull service
  ansible.builtin.command: systemctl enable ansible_pull.timer  # noqa command-instead-of-module
