---
- name: Reload systemd files
  systemd:
    daemon_reload: yes

# todo: use service module when fixed
# https://github.com/ansible/ansible/issues/48786
- name: Enable ansible_pull service
  command: systemctl enable ansible_pull.timer  # noqa 303
