---
name: ⚛️Molecule testing
on: [push]
jobs:
  molecule-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install vagrant and libvirt packages
        run: >
          sudo apt-get install --no-install-recommends
          libvirt-daemon-system
          vagrant-libvirt
          qemu-kvm
          libguestfs-tools
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install test runner
        run: |
          sudo python3 -m pip install tox

      - name: Install test dependencies
        run: sudo tox --notest

      - name: Run molecule tests
        run: sudo timeout 1h tox
